# @package _global_

model:
  use_structured_readout: True
  use_effect_model: True
  use_goal_progress_head: True
  use_reachability_head: True
  use_objectification: True

buffer:
  prioritized: True
