#!/bin/bash

# Shared defaults for the current structured Alien rerun track.
# Individual launches can still override any of these via environment vars.

STRUCTURED_ALIEN_MAX_PARALLEL_DEFAULT=${STRUCTURED_ALIEN_MAX_PARALLEL_DEFAULT:-2}
STRUCTURED_ALIEN_PAIR_PARALLEL_DEFAULT=${STRUCTURED_ALIEN_PAIR_PARALLEL_DEFAULT:-2}
STRUCTURED_ALIEN_BATCH_SIZE_DEFAULT=${STRUCTURED_ALIEN_BATCH_SIZE_DEFAULT:-16}
STRUCTURED_ALIEN_BATCH_LENGTH_DEFAULT=${STRUCTURED_ALIEN_BATCH_LENGTH_DEFAULT:-64}
STRUCTURED_ALIEN_ENV_NUM_DEFAULT=${STRUCTURED_ALIEN_ENV_NUM_DEFAULT:-4}
STRUCTURED_ALIEN_TRAIN_RATIO_DEFAULT=${STRUCTURED_ALIEN_TRAIN_RATIO_DEFAULT:-128}

